from enum import StrEnum

from pydantic import BaseModel


class ErrorCode(StrEnum):
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_EMAIL_VERIFICATION_INVALID = "AUTH_EMAIL_VERIFICATION_INVALID"
    AUTH_EMAIL_VERIFICATION_RATE_LIMITED = "AUTH_EMAIL_VERIFICATION_RATE_LIMITED"
    AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED"
    AUTH_ACCOUNT_PASSWORD_MISMATCH = "AUTH_ACCOUNT_PASSWORD_MISMATCH"
    AUTH_PASSWORD_RESET_INVALID = "AUTH_PASSWORD_RESET_INVALID"
    AUTH_GOOGLE_INVALID = "AUTH_GOOGLE_INVALID"
    AUTH_GOOGLE_ALREADY_LINKED = "AUTH_GOOGLE_ALREADY_LINKED"
    AUTH_GOOGLE_LINK_REQUIRED = "AUTH_GOOGLE_LINK_REQUIRED"
    AUTH_LAST_SIGN_IN_METHOD = "AUTH_LAST_SIGN_IN_METHOD"
    USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS"
    USER_NICKNAME_ALREADY_EXISTS = "USER_NICKNAME_ALREADY_EXISTS"
    WORKSPACE_PARENT_PAGE_NOT_FOUND = "WORKSPACE_PARENT_PAGE_NOT_FOUND"
    WORKSPACE_PAGE_NOT_FOUND = "WORKSPACE_PAGE_NOT_FOUND"
    WORKSPACE_INVALID_PAGE_MOVE = "WORKSPACE_INVALID_PAGE_MOVE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    HTTP_ERROR = "HTTP_ERROR"


class FieldError(BaseModel):
    field: str
    reason: str


class ErrorResponse(BaseModel):
    code: ErrorCode
    message: str
    errors: list[FieldError] | None = None
